### ISSUE TITLE
Could not initialize MesosSchedulerDriver

### ISSUE THREAD

**Issue by khatkar** [farmapromlab/rundeck-mesos-plugin#3]
After configuring the mesos plugin as described in the readme, rundeck fails to execute a docker job on mesos with message,
`1=PluginFailed: Could not initialize class org.apache.mesos.MesosSchedulerDriver`, status: failed`

Running mesos via docker using images mesosphere/master:1.1.0.0-2.0.107.ubuntu1404.02 and mesosphere/mesos-slave:1.1.0-2.0.107.ubuntu1404

**Comment by zolech** [comment]
Hi. Did you provide mesos native library for rundeck ? Check if /usr/lib/libmesos.so exists on a machine where rundeck is installed.

**Comment by khatkar** [comment]
Yes, I copied over the libmesos.so file form the mesos-master docker to the /usr/lib directory.

**Comment by zolech** [comment]
Please provide me an output of `ls -al /usr/lib | grep mesos`. Maybe the name of the file is wrong.

Also please check rundeck.log in case some errors shows up when it fails.

**Comment by khatkar** [comment]
Output of the ls command you provided is `-rwxr-xr-x   1   root   root  45297562 Nov 16 01:46 libmesos.so`

Relevant error logs are as follows:
* rundeck.log:
`[quartzScheduler_Worker-2] ERROR grails.app.services.rundeck.services.ExecutionUtilService - Execution failed: 8 in project Test: [Workflow result: , step failures: {1=PluginFailed: Could not initialize class org.apache.mesos.MesosSchedulerDriver}, status: failed]`

* service.log
`ERROR ExecutionUtilService: Execution failed: 8 in project Test: [Workflow result: , step failures: {1=PluginFailed: Could not initialize class org.apache.mesos.MesosSchedulerDriver}, status: failed]
`

**Comment by mdef** [comment]
+1 my output

```
# docker ps | grep 1f47542b1df8
1f47542b1df8        jordan/rundeck:latest  "/bin/sh -c 'EXTERNAL"   2 hours ago  


# docker exec -it 1f47542b1df8 ls /usr/lib/libmesos.so
/usr/lib/libmesos.so
# docker exec -it 1f47542b1df8 ls -al /usr/lib/ | grep mesos
lrwxrwxrwx  1 root root    17 Nov 16 01:46 libmesos.so -> libmesos-1.1.0.so
# docker cp 6622a26be785:/usr/lib/libmesos-1.1.0.so .
# docker cp libmesos-1.1.0.so 1f47542b1df8:/usr/lib/libmesos-1.1.0.so
# docker exec -it 1f47542b1df8 ls -al /usr/lib/ | grep mesos
-rwxr-xr-x  1 root root 45297562 Nov 16 01:46 libmesos-1.1.0.so
lrwxrwxrwx  1 root root       17 Nov 16 01:46 libmesos.so -> libmesos-1.1.0.so
```
the error is the same as in first message.

**Comment by mdef** [comment]
not the case any more
1. after copying compiled libmesos.so to /usr/lib/ directory rundeck should be restarted, but after restart more missing dependencies appears, so copying libmesos.so is not enough. 
2. after installing Mesos together with Rundeck no more errors.
Issue could be closed.

**Comment by zolech** [comment]
Hi,

jordan:rundeck image is based on debian jessie so libmesos-1.1.0.so compiled for that platform should have 45066176 bytes size. 

`-rwxr-xr-x  1 root root 45066176 Feb 19 09:46 libmesos-1.1.0.so
lrwxrwxrwx  1 root root       26 Feb 19 09:51 libmesos.so -> /usr/lib/libmesos-1.1.0.so
`

I've checked that size on couple of our servers. Your file is a little bit bigger so judging from that it wasn't compiled on that platform. Probably beacause of that there are missing dependencies.

By the way thank you for providing feedback! I will make some readme adjustments to cover this topic.
