### ISSUE TITLE
Fetch stderr and stdout from Mesos real time

### ISSUE THREAD

**Issue by haosdent** [farmapromlab/rundeck-mesos-plugin#6]
I am implementing this, would create a pull request later. :-)

**Comment by zolech** [comment]
Hi, how it's going with that feature ? We are also planning to look at this but don't want to double your work.

**Comment by haosdent** [comment]
hi @zolech Please go ahead. I stuck by other stuff and have not start this. It would be great if you could implement it and then I could use yours directly.

**Comment by zolech** [comment]
Done in v0.4
